USE [master]
GO

/****** Object:  Database [Zoo]    Script Date: 10/15/2019 23:19:08 ******/
CREATE DATABASE [Zoo] ON  PRIMARY 
( NAME = N'Zoo', FILENAME = N'D:\Zoo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Zoo_log', FILENAME = N'D:\Zoo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Zoo] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Zoo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Zoo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Zoo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Zoo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Zoo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Zoo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Zoo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Zoo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Zoo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Zoo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Zoo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Zoo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Zoo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Zoo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Zoo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Zoo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Zoo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Zoo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Zoo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Zoo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Zoo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Zoo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Zoo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Zoo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Zoo] SET  READ_WRITE 
GO

ALTER DATABASE [Zoo] SET RECOVERY FULL 
GO

ALTER DATABASE [Zoo] SET  MULTI_USER 
GO

ALTER DATABASE [Zoo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Zoo] SET DB_CHAINING OFF 
GO


USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_AnimalType]    Script Date: 10/15/2019 23:19:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_AnimalType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[info] [varchar](50) NULL,
	[ClassTypeId] [int] NULL,
 CONSTRAINT [PK_tbl_AnimalType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[tbl_AnimalType]  WITH CHECK ADD  CONSTRAINT [FK_tbl_AnimalType_tbl_AnimalType] FOREIGN KEY([ClassTypeId])
REFERENCES [dbo].[tbl_AnimalType] ([id])
GO

ALTER TABLE [dbo].[tbl_AnimalType] CHECK CONSTRAINT [FK_tbl_AnimalType_tbl_AnimalType]
GO


USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_StafRole]    Script Date: 10/15/2019 23:20:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_StafRole](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[definition] [varchar](50) NULL,
 CONSTRAINT [PK_tbl_StafRole] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_FoodType]    Script Date: 10/15/2019 23:20:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_FoodType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NULL,
	[parentId] [int] NULL,
 CONSTRAINT [PK_tbl_FoodType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[tbl_FoodType]  WITH CHECK ADD  CONSTRAINT [FK_tbl_FoodType_tbl_FoodType] FOREIGN KEY([parentId])
REFERENCES [dbo].[tbl_FoodType] ([id])
GO

ALTER TABLE [dbo].[tbl_FoodType] CHECK CONSTRAINT [FK_tbl_FoodType_tbl_FoodType]
GO


USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_VaccineType]    Script Date: 10/15/2019 23:20:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_VaccineType](
	[id] [int] NOT NULL,
	[description] [varchar](50) NULL,
 CONSTRAINT [PK_tbl_VaccineType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_VaccineDosage]    Script Date: 10/15/2019 23:21:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_VaccineDosage](
	[id] [int] NOT NULL,
	[vacinneTypeId] [int] NOT NULL,
	[animalId] [int] NOT NULL,
	[time] [date] NULL,
 CONSTRAINT [PK_tbl_VaccineDosage] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_Cages]    Script Date: 10/15/2019 23:21:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_Cages](
	[id] [int] NOT NULL,
	[descpription] [varchar](50) NULL,
	[capacity] [int] NULL,
 CONSTRAINT [PK_tbl_Cages] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_Staf]    Script Date: 10/15/2019 23:21:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_Staf](
	[id] [int] NOT NULL,
	[name] [varchar](50) NULL,
	[surname] [varchar](50) NULL,
	[birthDate] [datetime] NULL,
	[StartDate] [datetime] NULL,
	[stafRole] [int] NULL,
 CONSTRAINT [PK_tbl_Staf] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[tbl_Staf]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Staf_tbl_Staf] FOREIGN KEY([stafRole])
REFERENCES [dbo].[tbl_StafRole] ([id])
GO

ALTER TABLE [dbo].[tbl_Staf] CHECK CONSTRAINT [FK_tbl_Staf_tbl_Staf]
GO


USE [Zoo]
GO

/****** Object:  Table [dbo].[tbl_Parents]    Script Date: 10/15/2019 23:22:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_Parents](
	[id] [int] NOT NULL,
	[momId] [int] NOT NULL,
	[fatherID] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Parents] PRIMARY KEY CLUSTERED 
(
	[id] ASC,
	[momId] ASC,
	[fatherID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



